import './globals.css';
import { Noto_Sans_JP } from 'next/font/google';
import { GlobalHeader } from '@/components/Header';
import { GlobalBackground } from '@/components/Background';

const notoSansJp = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: any;
}) {
  return (
    <html lang="en">
      <body className={notoSansJp.className}>
        <GlobalBackground />
        <GlobalHeader />
        <main>{children}</main>
        {modal}
      </body>
    </html>
  );
}
